<div id="view-content">
<? if($this->form != null): echo $this->form; ?>
        <? else: ?>
        
    <table id="gradient-style">
	
	<tr>
		<th>ID</th>
		<th>Course</th>
		<th>Semester</th>
		<th>Lecturer</th>
		<th>Type</th>
		<th>Comment</th>
		<th>Files</th>
		<th></th>
	</tr>
 	
	<?php foreach ($this->exams as $entry): ?>
	<tr>
	<td>
		<div id="exam-id">
		<?php echo $entry->id ?>
		</div>
	</td>
	<td>
		<div id="exam-course">
			<?php 
			foreach($entry->course as $course)
			{
				echo "- ".$course;
				echo '<br>';
			} 
			foreach($entry->CourseConnected as $course)
			{
				echo "- ".$course ."*";
				echo '<br>';
			}
			?>
		</div>
	</td>
	<td>
		<div id="exam-semester">
			<? 
				echo $entry->semester;
			?>
		</div>
	</td>
	<td>
		<div id="exam-lecturer">    
			<? foreach($entry->Lecturer as $lecturer)
			{
				echo "- ".$lecturer;
				echo '<br>';
			} ?>
		</div>
	</td>
	<td>
	<div id="exam-infos">    
	<?
        echo $entry->Type;
        echo '<br>';
		echo $entry->SubType;
		echo '<br>';
		echo $entry->university;
		echo '<br>';
	    echo $entry->Autor;
    ?>
    </div>
	</td>
	<td>
	<div id="exam-comment" style="max-width:150px;">    
	<?
        echo $entry->comment;
    ?>
    </div>
	</td>
	<td>
	<div id="exam-files">
	<? foreach ($entry->documents as $id=>$document): ?>
    <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'download',
                  'id'=>$document->id),
            'default',
            true) ?>"><? echo $document->displayName.'.'.$document->extention; ?></a><?php if($document->collection) echo ' (collection)'; ?><br>
         <?php endforeach ?>   
	</div>
	</td>
	<td>
	<?php  $authManager = new Application_Model_AuthManager(); ?>
	<?
	if($authManager->isAllowed(null, 'approve_exam')): ?>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
				  'do'=>'disapprove',
                  'id'=>$entry->id),
            'default',
            true) ?>">disapprove</a><br>
			<? endif; ?>
	<a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'report',
                  'id'=>$entry->id),
            'default',
            true) ?>">report</a><br>
	<? if($authManager->isAllowed(null, 'view_log')): ?>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'log',
                  'id'=>$entry->id),
            'default',
            true) ?>">log</a><br>
			<? endif; ?>
	</td>
	</tr>
	<?php endforeach ?>
	</table>
    
    <? endif; ?>
	
	<p>* - connected to the origin Exam(s)</p>
    
</div>