<script>
var param;
$(document).ready(function () {
	param = {
			exam : <?php echo $this->exam; ?>,
			active_time : <?php echo '\'' . $this->year . '\''; ?>,
			active_page : 1,
			active_elements : 30,
			date : $("#datepicker").val(),
			comment : $("#comment").val()
		};

	$("#upload_time").val(param.active_time);

	$("#upload_img").attr("src", "/statistics/graph-download-exam?" + generateParams());

	  $("#upload_time").change(function() {
		  param.active_time = $("#upload_time").val();
		  $("#upload_img").attr("src", "/statistics/graph-download-exam?" + generateParams());
	  });
	/* assuming that text input datePicker would have id='datePicker' */
	$( "#datepicker" ).datepicker({ dateFormat: 'dd.mm.yy' });

});

function generateParams() {
	  var params = { };
	  if(param.active_time.match("^y")) {
	  	params['year'] = param.active_time.substring(1);
	  }
	  if(param.active_time.match("^ss") || param.active_time.match("^ws")) {
		  	params['semester'] = param.active_time.substring(1);
	  }
	  params['exam'] = param.exam;
	  params['date'] = param.date;
	  params['comment'] = param.comment;
	  return jQuery.param(params);
}

function addExamination() {
	param.date = $("#datepicker").val();
	param.comment = $("#comment").val();
	$.getJSON("/statistics/course-add-date",
			"" +generateParams(),
	    function(data){
			if(data != "ok") {
				alert("submit error");
			}
        });
	$("#datepicker").val("");
	$("#comment").val("");
	param.date = $("#datepicker").val();
	param.comment = $("#comment").val();
	$("#upload_img").attr("src", "/statistics/graph-download-exam?" + generateParams());
}
</script>

<div id="view-content">
	<h1>Download statistic course</h1>
	<div>
	  <select name="upload_time" id="upload_time">
	  <?php foreach($this->upload_years as $year)
			{
				echo ("<option value='y".$year."'>".$year."</option>");
			}
			?>
		<!-- <option value="ss13">SS 13</option>
		<option value="ws14">WS 13/14</option>-->
	  </select>
  	</div>
  	<div style="float: left;">
  		<img id="upload_img" src="">
  	</div>
  	<div style="float: right;">
  	Add course examination date:<br>
  	<input type="text" id="datepicker" size="10"><br>
  	Description:<br>
  	<input type="text" id="comment"><br>
  	<input type="button" value="add" onclick="javascript:addExamination()"><br>
  	<!-- <ul>
  		<li> sssss <input type="button"></li>
  	</ul>-->
  	</div>
  	<div style="clear: both;"></div>
</div>