<script>
var param;
$(document).ready(function () {
	param = {
			course : <?php echo $this->course; ?>,
			active_time : <?php echo '\'' . $this->year . '\''; ?>,
			active_page : 1,
			active_elements : 30,
			date : $("#datepicker").val(),
			comment : $("#comment").val()
		};

	$("#upload_time").val(param.active_time);

	updateRanking();
	$("#upload_img").attr("src", "/statistics/graph-download-course?" + generateParams());

	  $("#upload_time").change(function() {
		  param.active_time = $("#upload_time").val();
		  $("#upload_img").attr("src", "/statistics/graph-download-course?" + generateParams());
		  updateRanking();
	  });
	/* assuming that text input datePicker would have id='datePicker' */
	$( "#datepicker" ).datepicker({ dateFormat: 'dd.mm.yy' });

});

function generateParams() {
	  var params = { };
	  if(param.active_time.match("^y")) {
	  	params['year'] = param.active_time.substring(1);
	  }
	  if(param.active_time.match("^ss") || param.active_time.match("^ws")) {
		  	params['semester'] = param.active_time.substring(1);
	  }
	  params['course'] = param.course;
	  params['page'] = param.active_page;
	  params['elements'] = param.active_elements;
	  params['date'] = param.date;
	  params['comment'] = param.comment;
	  return jQuery.param(params);
}

function updateRanking() {
	  $.getJSON("/statistics/ajax-download-ranking-course2",
				""+generateParams(),
		        function(data){
				$( "#download_ranking" ).html("<table id=\"gradient-style\">\
						<tr>\
							<th>Rank</th>\
							<th>Down.</th>\
							<th>ID</th>\
							<th>Course</th>\
							<th>Semester</th>\
							<th>Lecturer</th>\
							<th>Type</th>\
							<th>Comment</th>\
							<th>Files</th>\
						</tr>");
				// set the default item if not set
				if(data.length == 0) {
					appendRankingElement("no data");
				}
		          $.each(data, function(i,item){
		        	  //setElmentsEditOn(i,item);
		        	  //$( "#download_ranking" ).html("");
		        	  
		        	  appendRankingElement(item);
		          });
		        });
}

function appendRankingElement(item) {
	var course = "";
	$.each(item['course'], function(i,item){
		course += "- <a href=\"/statistics/download-course?course="+item['id']+"&year="+param.active_time+"\">" + item['name'] + "</a><br>";
	});
	$.each(item['course_connected'], function(i,item){
		course += "- " + item + "*<br>";
	});
	var lecturer = "";
	$.each(item['lecturer'], function(i,item){
		lecturer += item + "<br>";
	});

	var files = "";
	$.each(item['files'], function(i,item){
		files += "<a href=\"/exams/download/id/"+item['id']+"\">"+item['name']+"</a><br>";
	});
	


	
	$( "#gradient-style" ).append(
	'<tr> \
	<td> \
	<div id="exam-rank"> \
	'+item['rank']+' \
	</div> \
</td> \
<td>\
	<div id="exam-downloads">\
	'+item['downloads']+'\
	</div>\
</td>\
<td>\
	<div id="exam-id">\
	<a href=\"/statistics/download-exam?exam='+item['idexam']+'&year='+param.active_time+'\">'+item['idexam']+'</a>\
	</div>\
</td>\
<td>\
	<div id="exam-course">\
		'+course+'\
	</div>\
</td>\
<td>\
	<div id="exam-semester">\
	'+item['semester']+' \
	</div> \
</td> \
<td> \
	<div id="exam-lecturer"> \
			'+lecturer+' \
	</div>\
</td>\
<td>\
	<div id="exam-infos">     \
		'+item['type']+'<br>'+item['sub_type']+'<br>'+item['uni']+'<br>\
	</div>\
</td>\
<td>\
	<div id="exam-comment" style="max-width:150px;">\
	'+item['comment']+' \
    </div>\
</td>\
<td>\
	<div id="exam-files">\
	    '+files+'  \
	</div>\
</td>\
</tr>');
}

function nextPage() {
	param.active_page += 1;
	updateRanking();
}
function previousPage() {
	if(param.active_page > 1) {
	param.active_page -= 1;
	updateRanking();
	}
}
function setMaxelements(max) {
	param.active_elements = max;
	updateRanking();
}

function addExamination() {
	param.date = $("#datepicker").val();
	param.comment = $("#comment").val();
	$.getJSON("/statistics/course-add-date",
			"" +generateParams(),
	    function(data){
			if(data != "ok") {
				alert("submit error");
			}
        });
	$("#datepicker").val("");
	$("#comment").val("");
	param.date = $("#datepicker").val();
	param.comment = $("#comment").val();
	$("#upload_img").attr("src", "/statistics/graph-download-course?" + generateParams());
}
</script>

<div id="view-content">
	<h1>Download statistic course</h1>
	<div>
	  <select name="upload_time" id="upload_time">
	  <?php foreach($this->upload_years as $year)
			{
				echo ("<option value='y".$year."'>".$year."</option>");
			}
			?>
		<!-- <option value="ss13">SS 13</option>
		<option value="ws14">WS 13/14</option>-->
	  </select>
  	</div>
  	<div style="float: left;">
  		<img id="upload_img" src="">
  	</div>
  	<div style="float: right;">
  	Add course examination date:<br>
  	<input type="text" id="datepicker" size="10"><br>
  	Description:<br>
  	<input type="text" id="comment"><br>
  	<input type="button" value="add" onclick="javascript:addExamination()"><br>
  	<!-- <ul>
  		<li> sssss <input type="button"></li>
  	</ul>-->
  	</div>
  	<div style="clear: both;"></div>
  	
  	  	<div id="download_ranking_pages" style="float: right;"><a href="#" onclick="javascript:previousPage()">Previous Page</a> - <a href="#" onclick="javascript:nextPage()">Next Page</a></div>
  	<div id="download_ranking_elements">Elements: <a href="#" onclick="javascript:setMaxelements(30);">30</a> <a href="#" onclick="javascript:setMaxelements(60);">60</a> <a href="#" onclick="javascript:setMaxelements(90);">90</a></div>
  	<div style="clear: both;"></div>
  	<div id="download_ranking">
    <table id="gradient-style">
	
	<tr>
		<th>Rank</th>
		<th>Down.</th>
		<th>ID</th>
		<th>Course</th>
		<th>Semester</th>
		<th>Lecturer</th>
		<th>Type</th>
		<th>Comment</th>
		<th>Files</th>
	</tr>
  	</div>

</div>