<div id="view-content">		
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'statistics',
                  'action'=>'upload'),
            'default',
            true) ?>">Statistic Uploads</a></li>
            <li><a href="<?php echo $this->url(
            array('controller'=>'statistics',
                  'action'=>'download'),
            'default',
            true) ?>">Statistic Downloads</a></li>
		</ul>
</div>