<br /><br />
<style>
#gradient-style
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	/* margin: 45px; */
	width: 100%;
	text-align: left;
	border-collapse: collapse;
}
#gradient-style th
{
	font-size: 13px;
	font-weight: normal;
	padding: 8px;
	background: #b9c9fe url('table-images/gradhead.png') repeat-x;
	border-top: 2px solid #d3ddff;
	border-bottom: 1px solid #fff;
	color: #039;
}
#gradient-style td
{
	padding: 8px; 
	border-bottom: 1px solid #fff;
	color: #669;
	border-top: 1px solid #fff;
	background: #e8edff url('table-images/gradback.png') repeat-x;
}
#gradient-style tfoot tr td
{
	background: #e8edff;
	font-size: 12px;
	color: #99c;
}
#gradient-style tbody tr:hover td
{
	background: #d0dafd url('table-images/gradhover.png') repeat-x;
	color: #339;
}
</style>
<div id="view-content">
	<p>View script for controller <b>ExamsAdmin</b> and script/action name <b>editfiles</b></p>
    <?
        echo $this->form; 
    ?>
    <hr>
    <a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'editfiles',
                  'id'=>$this->exam,
				  'files'=>$this->files),
            'default',
            true) ?>">Add more Files</a><br>
    <?
        echo $this->form2; 
    ?>
</div>