<br /><br />
<div id="view-content">
	<p>View script for controller <b>ExamsAdmin</b> and script/action name <b>index</b></p>
		<ul>
			<li><a href="<?php echo $this->url(
            	array('controller'=>'exams-admin',
                	  'action'=>'overview'),
            			'default', true) ?>">
            			Overview</a></li>
            
    <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'build-quicksearch-index'),
            'default',
            true) ?>">Quicksearch Index</a></li>
	
		</ul>
</div>