<div id="view-content">
		<ul>
			<li><a href="<?php echo $this->url(
            	array('controller'=>'exams-admin',
                	  'action'=>'overview'),
            			'default', true) ?>">
            			Overview</a></li>
            			</ul>
    <ul>        
    <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'degree-group-add'),
            'default',
            true) ?>">Add degree groups</a></li>
   <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'degree-group-edit'),
            'default',
            true) ?>">Edit degree groups</a></li>
   <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'degree-add'),
            'default',
            true) ?>">Add degree</a></li>
    <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'degree-edit'),
            'default',
            true) ?>">Edit degree</a></li>
    <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'course-add'),
            'default',
            true) ?>">Add course</a></li>
    <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'degree'),
            'default',
            true) ?>">degree</a></li>
    <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'course-edit'),
            'default',
            true) ?>">Edit course</a></li>
     <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'course'),
            'default',
            true) ?>">course</a></li>
    <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'lecturer-add'),
            'default',
            true) ?>">Add lecturer</a></li>
    <li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'lecturer-edit'),
            'default',
            true) ?>">Edit lecturer</a></li>
            </ul>
    <ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'activity-log'),
            'default',
            true) ?>">Activity log</a></li>
		</ul>
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'quicksearch-index'),
            'default',
            true) ?>">Quicksearch Index</a></li>
		</ul>
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'pad',
                  'action'=>'index'),
            'default',
            true) ?>">Pads</a></li>
		<ul>
		<li><a href="<?php echo $this->url(
            array('controller'=>'pad',
                  'action'=>'overview'),
            'default',
            true) ?>">Pad overview</a></li>
            </ul>
		</ul>
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'maintenance'),
            'default',
            true) ?>">Maintenance</a></li>
		</ul>
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'statistics',
                  'action'=>''),
            'default',
            true) ?>">Statistics</a></li>
		</ul>	
</div>