<div id="view-content">
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'maintenance',
                  'do'=>'checkInconsistency',
                  ),
            'default',
            true) ?>">Check inconsistency</a> (will throw a exeption on fail)<br><I>Grep all exams and construct there model, will take up to several mins</I></li>
		</ul>
		
		<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'maintenance',
                  'do'=>'resetAllMimeTypes',
                  ),
            'default',
            true) ?>">Reset all MIME-types</a></li>
		</ul>
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'maintenance',
                  'do'=>'ckeckFiles',
                  ),
            'default',
            true) ?>">Ckeck all files</a></li>
		</ul>
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'maintenance',
                  'do'=>'checkExtention',
                  ),
            'default',
            true) ?>">Ckeck all file extention</a></li>
		</ul>
		<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'maintenance',
                  'do'=>'checkFileDamaged',
                  ),
            'default',
            true) ?>">Check for damaged files</a></li>
		</ul>
		<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'maintenance',
                  'do'=>'generateMd5',
                  ),
            'default',
            true) ?>">Generate md5 sums (if missing)</a></li>
		</ul>
		
		
		
	
</div>