<style>
#gradient-style
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	/* margin: 45px; */
	width: 100%;
	text-align: left;
	border-collapse: collapse;
}
#gradient-style th
{
	font-size: 13px;
	font-weight: normal;
	padding: 8px;
	background: #b9c9fe url('table-images/gradhead.png') repeat-x;
	border-top: 2px solid #d3ddff;
	border-bottom: 1px solid #fff;
	color: #039;
}
#gradient-style td
{
	padding: 8px; 
	border-bottom: 1px solid #fff;
	color: #669;
	border-top: 1px solid #fff;
	background: #e8edff url('table-images/gradback.png') repeat-x;
}
#gradient-style tfoot tr td
{
	background: #e8edff;
	font-size: 12px;
	color: #99c;
}
#gradient-style tbody tr:hover td
{
	background: #d0dafd url('table-images/gradhover.png') repeat-x;
	color: #339;
}
</style>
<div id="view-content">
	<? if($this->form != null): echo $this->form; ?>
        <? else: ?>
    <h2>Unchecked</h2>
    <table id="gradient-style">
	
	<tr>
		<th>ID</th>
		<th>Course</th>
		<th>Semester</th>
		<th>Lecturer</th>
		<th>Type</th>
		<th>Files</th>
		<th>Comment</th>
		<th>Options</th>
	</tr>
 	
	<?php foreach ($this->exams as $entry): ?>
	<tr>
	<td>
		<div id="exam-id">
		<?php echo $entry->id ?>
		</div>
	</td>
	<td>
		<div id="exam-course">
			<?php 
			foreach($entry->course as $course)
			{
				echo "- ".$course;
				echo '<br>';
			} 
			foreach($entry->CourseConnected as $course)
			{
				echo "- ".$course ."*";
				echo '<br>';
			}
			?>
		</div>
	</td>
	<td>
		<div id="exam-semester">
			<? 
				echo $entry->semester;
			?>
		</div>
	</td>
	<td>
		<div id="exam-lecturer">    
			<? foreach($entry->Lecturer as $lecturer)
			{
				echo "- ".$lecturer;
				echo '<br>';
			} ?>
		</div>
	</td>
	<td>
	<div id="exam-infos">    
	<?
        echo $entry->Type;
        echo '<br>';
		echo $entry->SubType;
		echo '<br>';
		echo $entry->university;
		echo '<br>';
	    echo $entry->Autor;
    ?>
    </div>
	</td>
	<td>
	<div id="exam-files">
	<? foreach ($entry->documents as $id=>$document): ?>
    <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'download',
                  'admin'=>$document->id),
            'default',
            true) ?>">File <? echo $id+1; ?></a> [<? echo $document->mimeType; ?>]<br>
         <?php endforeach ?>   
	</div>
	</td>
	<td>
	<div id="exam-comment" style="max-width:150px;">    
	<?
        echo $entry->comment;
    ?>
    </div>
	</td>
	<td>
		<div id="exam-control">
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
                  'do'=>'delete',
                  'id'=>$entry->id),
            'default',
            true) ?>">delete</a><br>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
                  'do'=>'edit',
                  'id'=>$entry->id),
            'default',
            true) ?>">edit</a><br>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
                  'do'=>'edit-files',
                  'id'=>$entry->id),
            'default',
            true) ?>">edit files</a><br>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
                  'do'=>'approve',
                  'id'=>$entry->id),
            'default',
            true) ?>">approve</a><br>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
                  'do'=>'log',
                  'id'=>$entry->id),
            'default',
            true) ?>">log</a><br>
		</div>
	</td>
	</tr>
	<?php endforeach ?>
	</table>
    
    <? endif; ?>
    
    <p>* - connected to the origin Exam(s)</p>
    
    
    <!-- Reported -->
    
    	<? if($this->form != null): echo $this->form; ?>
        <? else: ?>
        
    <h2>Reported</h2>
        
    <table id="gradient-style">
	
	<tr>
		<th>ID</th>
		<th>Course</th>
		<th>Semester</th>
		<th>Lecturer</th>
		<th>Type</th>
		<th>Files</th>
		<th>Comment</th>
		<th>Options</th>
	</tr>
 	
	<?php foreach ($this->exams_reported as $entry): ?>
	<tr>
	<td>
		<div id="exam-id">
		<?php echo $entry->id ?>
		</div>
	</td>
	<td>
		<div id="exam-course">
			<?php 
			foreach($entry->course as $course)
			{
				echo "- ".$course;
				echo '<br>';
			} 
			foreach($entry->CourseConnected as $course)
			{
				echo "- ".$course ."*";
				echo '<br>';
			}
			?>
		</div>
	</td>
	<td>
		<div id="exam-semester">
			<? 
				echo $entry->semester;
			?>
		</div>
	</td>
	<td>
		<div id="exam-lecturer">    
			<? foreach($entry->Lecturer as $lecturer)
			{
				echo "- ".$lecturer;
				echo '<br>';
			} ?>
		</div>
	</td>
	<td>
	<div id="exam-infos">    
	<?
        echo $entry->Type;
        echo '<br>';
		echo $entry->SubType;
		echo '<br>';
		echo $entry->university;
		echo '<br>';
	    echo $entry->Autor;
    ?>
    </div>
	</td>
	<td>
	<div id="exam-files">
	<? foreach ($entry->documents as $id=>$document): ?>
    <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'download',
                  'admin'=>$document->id),
            'default',
            true) ?>">File <? echo $id+1; ?></a> [<? echo $document->mimeType; ?>]<br>
         <?php endforeach ?>   
	</div>
	</td>
	<td>
	<div id="exam-comment" style="max-width:150px;">    
	<?
        echo $entry->comment;
    ?>
    </div>
	</td>
	<td>
		<div id="exam-control">
				<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
                  'do'=>'unreport',
                  'id'=>$entry->id),
            'default',
            true) ?>">remove report</a><br>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
                  'do'=>'disapprove',
                  'id'=>$entry->id),
            'default',
            true) ?>">disapprove</a><br>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'overview',
                  'do'=>'log',
                  'id'=>$entry->id),
            'default',
            true) ?>">log</a><br>
		</div>
	</td>
	</tr>
	<?php endforeach ?>
	</table>
    
    <? endif; ?>
    
</div>