  	<style>
#gradient-style
{
	font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
	font-size: 12px;
	/* margin: 45px; */
	width: 100%;
	text-align: left;
	border-collapse: collapse;
}
#gradient-style th
{
	font-size: 13px;
	font-weight: normal;
	padding: 8px;
	background: #b9c9fe repeat-x;
	border-top: 2px solid #d3ddff;
	border-bottom: 1px solid #fff;
	color: #039;
}
#gradient-style td
{
	padding: 8px; 
	border-bottom: 1px solid #fff;
	color: #669;
	border-top: 1px solid #fff;
	background: #e8edff repeat-x;
}
#gradient-style tfoot tr td
{
	background: #e8edff;
	font-size: 12px;
	color: #99c;
}
#gradient-style tbody tr:hover td
{
	background: #d0dafd repeat-x;
	color: #339;
}
</style>
<script>
var param;
$(document).ready(function () {
	param = {
			course : <?php echo $this->course; ?>,
			active_time : $("#upload_time").val()
		};

	$("#upload_img").attr("src", "/exams-admin/statistics-graph-download-course?" + generateParams());

	  $("#upload_time").change(function() {
		  param.active_time = $("#upload_time").val();
		  $("#upload_img").attr("src", "/exams-admin/statistics-graph-download-course?" + generateParams());	  
	  });
});

function generateParams() {
	  var params = { };
	  if(param.active_time.match("^y")) {
	  	params['year'] = param.active_time.substring(1);
	  }
	  if(param.active_time.match("^ss") || param.active_time.match("^ws")) {
		  	params['semester'] = param.active_time.substring(1);
	  }
	  params['course'] = param.course;
	  return jQuery.param(params);
}
</script>

<div id="view-content">
	<h1>Download statistic course</h1>
	<div>
	  <select name="upload_time" id="upload_time">
	  <?php foreach($this->upload_years as $year)
			{
				echo ("<option value='y".$year."'>".$year."</option>");
			}
			?>
		<!-- <option value="ss13">SS 13</option>
		<option value="ws14">WS 13/14</option>-->
	  </select>
  	</div>
  	<div>
  		<img id="upload_img" src="">
  	</div>

</div>