<script> 
$(document).ready(function () {
	  $("#upload_time").change(function() { 
		  //alert ("hello");
		  var params = { year : $("#upload_time").val().substring(1) };
		  //alert(jQuery.param(params));
		  $("#upload_img").attr("src", "http://testdb.fachschaft.tf/exams-admin/statisticsg1?" + jQuery.param(params));
		  
	  })
});
</script>

<div id="view-content">
	<h1>Upload statistics</h1>
	<div>
	  <select name="upload_time" id="upload_time">
	    <option value="y2013">2013</option>
	    <option value="y2012">2012</option>
	  </select>
	  <select name="upload_degree" id="upload_degree">
	  	<option value="-1">ALL</option>
	    <option value="1">ESE Bsc.</option>
	    <option value="9">Info Bsc.</option>
	  </select>
  	</div>
  	<div>
  		<img id="upload_img" src="http://testdb.fachschaft.tf/exams-admin/statisticsg1?year=2013">
  	</div>  	
</div>