<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Exam Database</title>
   <?php
            $this->headLink()
                //->prependStylesheet('/css/global.css')
            	->appendStylesheet('/css/table.css')
                ->appendStylesheet('/css/smoothness/jquery-ui-1.10.3.custom.min.css');
            	
            
        ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->jQuery()
                        ->setLocalPath('/js/jquery-1.9.1.js')
        				->setUiLocalPath('/js/jquery-ui-1.10.3.custom.min.js'); ?>
   
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: <? if(!Application_Model_AuthManager::hasIdentity()): echo "30px";  else: echo "45px"; endif; ?>;">
    <div id="header-logo" style="float: left">
        <b>Exam Database</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'groups'),
            'default',
            true) ?>">Search</a>
        <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'quick-search'),
            'default',
            true) ?>">Quicksearch</a>      
        <a href="<?php echo $this->url(
            array('controller'=>'exams-upload',
                  'action'=>'index'),
            'default',
            true) ?>">Upload</a>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'index'),
            'default',
            true) ?>">Admin</a>
        <br>
         <div id="header-navigation-2" style="float: right">
		<? if(!Application_Model_AuthManager::hasIdentity()): ?>
		<!-- <a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'login'),
            'default',
            true) ?>">Login</a>-->
		<? else: ?>	
		
		<?php echo Application_Model_AuthManager::getIdentity() . " (" . Application_Model_AuthManager::getRole() .")" ?> - (<a href="<?php echo $this->url(
            array('controller'=>'login',
                  'action'=>'logout'),
            'default',
            true) ?>">Logout</a>)
			<? endif; ?>
			</div>
    </div>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>