<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Exam Database</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
 <?php
            $this->headLink()
                ->prependStylesheet('/css/style.css')
                ->prependStylesheet('/css/quickseach.css')
            	->appendStylesheet('/css/table.css')
            	->appendStylesheet('/css/form.css')
                ->appendStylesheet('/css/smoothness/jquery-ui-1.10.3.custom.min.css');
            	
            
        ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->jQuery()
                        ->setLocalPath('/js/jquery-1.9.1.js')
        				->setUiLocalPath('/js/jquery-ui-1.10.3.custom.min.js'); ?>
<!--[if IE]>
<style type="text/css">
#sidebar #calendar {
	background-position: 0px 20px;
}
</style>
<![endif]-->
</head>
<body>
<div id="logo">
	<h1><a href="/">Exam Database</a></h1>
</div>
<div id="menu">
	<ul>
		<li class="first">
	        <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'groups'),
            'default',
            true) ?>">Search</a>
            </li>
        <li><a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'quick-search'),
            'default',
            true) ?>">Quicksearch</a></li>      
        <li><a href="<?php echo $this->url(
            array('controller'=>'exams-upload',
                  'action'=>'index'),
            'default',
            true) ?>">Upload</a></li>
		<li><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'index'),
            'default',
            true) ?>">Admin</a></li>

         <span id="header-navigation-2" class="right">
         
		<? if(!Application_Model_AuthManager::hasIdentity()): ?>
		<li class="first"><a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'index'),
            'default',
            true) ?>">Login</a>
		<? else: ?></li>	
		
		
		<li class="first"><?php echo Application_Model_AuthManager::getIdentity() . " - " . Application_Model_AuthManager::getRole() ?></li>
		<li>
		 <a href="<?php echo $this->url(
            array('controller'=>'login',
                  'action'=>'logout'),
            'default',
            true) ?>">Logout</a>
			<? endif; ?>
			</li>
			</span>
		</ul>
		<div style="clear: both;"></div>
	<!-- <div id="search">
		<form method="get" action="">
			<fieldset>
			<input id="s" type="text" name="s" value="" />
			<input id="x" type="image" name="imageField" src="/images/img10.jpg" />
			</fieldset>
		</form>
	</div>-->
</div>
<hr />
<div id="banner">
	<!-- <img src="/images/img04.jpg" alt="" width="960" height="147" /> -->
</div>
<!-- start page -->
<div id="page">
	<!-- start content -->
	<div id="content-full">
	<div class="post">
	<?php echo $this->layout()->content ?>
		
			<!-- <h2 class="title"><a href="#">Welcome to FrozenAge</a></h2>
			<div class="entry">
				<h3>A free CSS template by NodeThirtyThree for Free CSS Templates</h3>
				<img src="/images/img06.jpg" alt="" width="132" height="72" class="left" />
				<p>This is <strong>FrozenAge</strong>, a free, fully standards-compliant CSS template designed by <a href="http://www.nodethirtythree.com/">NodeThirtyThree</a> for <a href="http://www.freecsstemplates.org/" rel="nofollow">FreeCSSTemplates.org</a>. The photos in this design are from <a href="http://www.pdphoto.org/">PDPhoto.org</a>.</p>
				<p>This free template is released under a <a href="#">Creative Commons Attributions 2.5</a> license, so you’re pretty much free to do whatever you want with it (even use it commercially) provided you keep the links in the footer intact. Aside from that, have fun with it :)  This design is also available as a <a href="http://www.freewpthemes.net/preview/frozenage/">WordPress theme</a> at <a href="http://www.freewpthemes.net/">Free Wordpress Themes</a>.</p>
			</div>
			<p class="meta">Posted on November 5, 2007 by <a href="#">Someone</a> &nbsp;|&nbsp; <a href="#">32 comments</a></p>
		</div>
		<div class="post">
			<h2 class="title"><a href="#">Blandit volutpat consequat</a></h2>
			<div class="entry">
				<h3>Prom nec magna tempus lorem ipsum dolor</h3>
				<p>Proin nec magna. Proin nec massa sit amet purus congue molestie. Aliquam erat volutpat. Nulla pellentesque dolor non tellus. Duis vel elit sit amet ipsum vehicula varius. Vestibulum ante ipsum primis in <a href="#">faucibus orci luctus et ultrices</a> posuere cubilia Curae; Suspendisse rhoncus. Nunc est. Praesent interdum lectus quis neque. Aliquam eros. Nulla fermentum dolor eget mi. Cras diam sapien, auctor non, malesuada at, tristique id, dui. Aenean congue ante. </p>
				<p>Proin nec magna. Proin nec massa sit amet purus congue molestie. Aliquam erat volutpat. Nulla pellentesque dolor non tellus. Duis vel elit sit amet <a href="#">ipsum vehicula varius</a>. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae.</p>
			</div>
			<p class="meta">Posted on November 5, 2007 by <a href="#">Someone</a> &nbsp;|&nbsp; <a href="#">32 comments</a></p>-->
		</div>
	</div>
	<!-- end content -->
	<!-- start sidebar -->
	<!-- <div id="sidebar">
		<ul>
			<li id="calendar">
				<table summary="Calendar">
					<caption>
					November 2007
					</caption>
					<thead>
						<tr>
							<th abbr="Monday" scope="col" title="Monday">M</th>
							<th abbr="Tuesday" scope="col" title="Tuesday">T</th>
							<th abbr="Wednesday" scope="col" title="Wednesday">W</th>
							<th abbr="Thursday" scope="col" title="Thursday">T</th>
							<th abbr="Friday" scope="col" title="Friday">F</th>
							<th abbr="Saturday" scope="col" title="Saturday">S</th>
							<th abbr="Sunday" scope="col" title="Sunday">S</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<td abbr="October" colspan="3" id="prev"><a href="http://wordpress.local/?m=200710" title="View posts for October 2007">&laquo; Oct</a></td>
							<td class="pad">&nbsp;</td>
							<td abbr="December" colspan="3" id="next"><a href="http://wordpress.local/?m=200710" title="View posts for December 2007">Dec &raquo;</a></td>
						</tr>
					</tfoot>
					<tbody>
						<tr>
							<td colspan="3" class="pad">&nbsp;</td>
							<td>1</td>
							<td>2</td>
							<td>3</td>
							<td>4</td>
						</tr>
						<tr>
							<td id="today">5</td>
							<td>6</td>
							<td>7</td>
							<td>8</td>
							<td>9</td>
							<td>10</td>
							<td>11</td>
						</tr>
						<tr>
							<td>12</td>
							<td>13</td>
							<td>14</td>
							<td>15</td>
							<td>16</td>
							<td>17</td>
							<td>18</td>
						</tr>
						<tr>
							<td>19</td>
							<td>20</td>
							<td>21</td>
							<td>22</td>
							<td>23</td>
							<td>24</td>
							<td>25</td>
						</tr>
						<tr>
							<td>26</td>
							<td>27</td>
							<td>28</td>
							<td>29</td>
							<td>30</td>
							<td class="pad" colspan="2">&nbsp;</td>
						</tr>
					</tbody>
				</table>
			</li>
			<li>
				<h2>Etiam dolore</h2>
				<p>Nulla pellentesque dolor non tellus. Duis vel elit sit <a href="#">amet ipsum vehicula</a> varius. Vestibulum ante ipsum primis in faucibus orci luctus.</p>
			</li>
			<li>
				<h2>Consequat lorem</h2>
				<ul>
					<li><a href="#">Proin nec magna nec massa</a></li>
					<li><a href="#">Sit amet purus congue</a></li>
					<li><a href="#">Molestie aliquam erat volutpat</a></li>
					<li><a href="#">Nulla pellentesque dolor</a></li>
					<li><a href="#">Non tellus duis vel elit sit</a></li>
					<li><a href="#">Amet ipsum vehicula varius</a></li>
					<li><a href="#">Primis in faucibus orci luctus</a></li>
					<li><a href="#">Vestibulum ante ipsum</a></li>
				</ul>
			</li>
		</ul>
	</div>-->
	<!-- end sidebar -->
</div>
<!-- end page -->
<div id="footer">
	<p class="legal">Copyright (c) <?php echo date("Y"); ?>. All rights reserved.</p>
</div>
</body>
</html>
<!-- 
<body>
<div id="header" style="background-color: #EEEEEE; height: <? if(!Application_Model_AuthManager::hasIdentity()): echo "30px";  else: echo "45px"; endif; ?>;">
    <div id="header-logo" style="float: left">
        <b>Exam Database</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'groups'),
            'default',
            true) ?>">Search</a>
        <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'quick-search'),
            'default',
            true) ?>">Quicksearch</a>      
        <a href="<?php echo $this->url(
            array('controller'=>'exams-upload',
                  'action'=>'index'),
            'default',
            true) ?>">Upload</a>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'index'),
            'default',
            true) ?>">Admin</a>
        <br>
         <div id="header-navigation-2" style="float: right">
		<? if(!Application_Model_AuthManager::hasIdentity()): ?>
		<!-- <a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'login'),
            'default',
            true) ?>">Login</a>-->
		<!--<? else: ?>	
		
		<?php echo Application_Model_AuthManager::getIdentity() . " (" . Application_Model_AuthManager::getRole() .")" ?> - (<a href="<?php echo $this->url(
            array('controller'=>'login',
                  'action'=>'logout'),
            'default',
            true) ?>">Logout</a>)
			<? endif; ?>
			</div>
    </div>
</div>
 
</body>
</html>-->
