<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Exam Database</title>
  <?php echo $this->headLink()->appendStylesheet('/css/global.css') ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>Exam Database</b>
    </div>
    <div id="header-navigation" style="float: right">
        <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'groups'),
            'default',
            true) ?>">Search</a>
        <a href="<?php echo $this->url(
            array('controller'=>'exams',
                  'action'=>'upload'),
            'default',
            true) ?>">Upload</a>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'index'),
            'default',
            true) ?>">Admin</a>
		<? if(!Zend_Auth::getInstance()->hasIdentity()): ?>
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'login'),
            'default',
            true) ?>">Login</a>
		<? else: ?>	
		<a href="<?php echo $this->url(
            array('controller'=>'exams-admin',
                  'action'=>'logout'),
            'default',
            true) ?>">Logout</a>
			<? endif; ?>
    </div>
</div>
 
<?php echo $this->layout()->content ?>
 
</body>
</html>