<div id="view-content">		
	<ul>
	<li><a href="<?php echo $this->url(
            array('controller'=>'pad',
                  'action'=>'overview'),
            'default',
            true) ?>">Pad overview</a></li>
            <li><a href="<?php echo $this->url(
            array('controller'=>'pad',
                  'action'=>'maintenance'),
            'default',
            true) ?>">Pad maintenance</a></li>
		</ul>
</div>